// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyAWDgs6-Wtp-T7men3zkNV3NY9C97_d9Pc',
      appId: '1:787127435616:android:e2c438ca862326dfb79e05',
      messagingSenderId: '787127435616',
      projectId: 'bimbel-8aaaf',
      storageBucket: 'bimbel-8aaaf.firebasestorage.app');

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyAWDgs6-Wtp-T7men3zkNV3NY9C97_d9Pc',
      appId: '1:787127435616:android:e2c438ca862326dfb79e05',
      messagingSenderId: '787127435616',
      projectId: 'bimbel-8aaaf',
      storageBucket: 'bimbel-8aaaf.firebasestorage.app');
}
